# Generated by Django 3.0.7 on 2020-06-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date published')),
                ('time', models.TimeField(verbose_name='time published')),
                ('location', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
